Add registration scenario
kmatlaha/kmatlaha pull request #1
Opened 2022-12-11 20:13 UTC by kmatlaha

Add registration scenario

2022-12-11 21:34 UTC, adudyak requested changes

2022-12-11 21:34 UTC, adudyak commented on tests/store_test.js
> +    I.see('Your Account Has Been Created!');
use your method in register.js

2022-12-11 21:34 UTC, adudyak commented on tests/store_test.js
> +    pause();
remove pause()

2022-12-11 21:34 UTC, adudyak commented on tests/store_test.js
> +    passwordConfirm: 'Temp12345',
remove passwordConfirm, use password

2022-12-11 21:34 UTC, adudyak commented on steps_file.js
> +      this.amOnPage (STORE_URL);
remove space this.amOnPage(STORE_URL);

2022-12-17 23:28 UTC, kmatlaha commented on tests/store_test.js
> +    I.see('Your Account Has Been Created!');
fixed

2022-12-17 23:28 UTC, kmatlaha commented on tests/store_test.js
> +    pause();
fixed

2022-12-17 23:28 UTC, kmatlaha commented on tests/store_test.js
> +    passwordConfirm: 'Temp12345',
fixed

2022-12-17 23:28 UTC, kmatlaha commented on steps_file.js
> +      this.amOnPage (STORE_URL);
fixed

2022-12-20 19:26 UTC, closed without merging