buy many products scenario
kmatlaha/kmatlaha pull request #3
Opened 2022-12-22 18:47 UTC by kmatlaha

buy many products scenario

2022-12-22 22:08 UTC, adudyak requested changes

2022-12-22 22:08 UTC, adudyak commented on tests/buyProducts_test.js
> +
remove empty line

2022-12-22 22:08 UTC, adudyak commented on tests/buyProducts_test.js
> +productLinks.add (['http://opencart.qatestlab.net/index.php?route=product/product&path=31&product_id=74']);
remove DataTable

2022-12-22 22:08 UTC, adudyak commented on tests/buyProducts_test.js
> +const { getArrayOfProductLinkObjects } = require('../helpers/productLinksGetter');
not used - remove

2022-12-22 22:08 UTC, adudyak commented on tests/buyProducts_test.js
> +let productLinks2 = LinksGetter.getLinks();
name variable `productLinks`

2022-12-24 18:12 UTC, kmatlaha commented on tests/buyProducts_test.js
> +
I did not find these lines in my code.

2022-12-24 18:12 UTC, kmatlaha commented on tests/buyProducts_test.js
> +productLinks.add (['http://opencart.qatestlab.net/index.php?route=product/product&path=31&product_id=74']);
Removed.

2022-12-24 18:12 UTC, kmatlaha commented on tests/buyProducts_test.js
> +const { getArrayOfProductLinkObjects } = require('../helpers/productLinksGetter');
Removed.

2022-12-24 18:12 UTC, kmatlaha commented on tests/buyProducts_test.js
> +let productLinks2 = LinksGetter.getLinks();
Changed.

2022-12-25 19:24 UTC, merged